# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('sno', models.CharField(max_length=10)),
                ('resumeid', models.CharField(max_length=30 ,primary_key=True)),
                ('name', models.CharField(max_length=30)),
                ('otp', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('Attend', models.CharField(max_length=30)),

            ],
        ),
    ]
