# Generated by Django 3.2.2 on 2021-05-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='otp',
            field=models.CharField(max_length=20),
        ),
    ]
